# Generated by Django 5.2.1 on 2025-06-14 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electric', 'Electric'), ('Luxury', 'Luxury'), ('SUV', 'SUV'), ('Sports', 'Sports'), ('Supercar', 'Supercar'), ('Ultra luxury', 'Ultra Luxury')], default='electric', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.TextField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('IMT', 'Intelligent Manual Transmission')], default='automatic', max_length=20)),
                ('fuelType', models.CharField(choices=[('Electric', 'Electric'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hydrogen', 'Hydrogen'), ('Hybrid', 'Hybrid')], default='electric', max_length=30)),
                ('seats', models.IntegerField()),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('specifications', models.JSONField(default=dict)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
