# Generated by Django 5.2.3 on 2026-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_address_booking_agree_to_terms_booking_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Luxury', 'Luxury'), ('SUV', 'SUV'), ('Sports', 'Sports'), ('Supercar', 'Supercar'), ('Ultra luxury', 'Ultra Luxury')], default='Electric', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hydrogen', 'Hydrogen'), ('Hybrid', 'Hybrid')], default='Electric', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('IMT', 'Intelligent Manual Transmission')], default='Automatic', max_length=20),
        ),
    ]
